name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update trunk-cached branch with trunk
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin trunk-cached
          git switch trunk-cached
          git merge ${{ github.sha }} || git merge --allow-unrelated-histories ${{ github.sha }}
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
