name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trunk-cached branch
        run: |
          # git config --global user.name "GitHub Actions"
          # git config --global user.email "actions@github.com"
          git checkout trunk-cached || git checkout -b trunk-cached

      - name: Merge Latest Commit from Trunk
        run: |
          git fetch origin trunk
          git merge ${{ github.sha }} --no-edit
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
