name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: trunk-cached
      
      - name: Git log test
        run: |
          git fetch origin trunk
          git fetch origin trunk-cached
          echo
          echo 'trunk ==============================================='
          git log --oneline origin/trunk
          echo
          echo 'trunk-cached ========================================'
          git log --oneline origin/trunk-cached
          

      - name: Update trunk-cached branch
        run: |
          git fetch origin trunk-cached
          git switch trunk-cached
          git rebase origin/trunk-cached
          git merge --ff-only ${{ github.sha }}
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
