name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update trunk-cached branch with trunk
        run: |
          git checkout trunk-cached || git checkout -b trunk-cached
          git fetch origin trunk
          git pull origin trunk-cached
          git merge origin/trunk --no-edit
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
