name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update trunk-cached branch with trunk
        run: |
          git branch
          git switch -c trunk-cached
          if git fetch origin trunk-cached; then
            git reset --hard origin/trunk-cached
          else
            echo 'Remote ref does not exist'
          fi
          git log --oneline
          git merge ${{ github.sha }}
          git log --oneline
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
