name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cache-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch the latest trunk and refs/cache/trunk
        run: |
          git fetch origin refs/cache/latest:refs/cache/latest || echo "No trunk cache ref exists"

      - name: Update the cache ref to latest trunk commit
        run: |
          git update-ref refs/cache/trunk ${{ github.sha }}

      - name: Push updated trunk cache ref
        run: |
          git push origin refs/cache/trunk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
