name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a local trunk-cached branch
        run: |
          if git switch trunk-cached; then
            git pull origin trunk-cached
          else
            git switch -c trunk-cached
          fi

      - name: Pull trunk-cached branch
        run: |
          git fetch origin trunk-cached || echo "No trunk-cached branch exists yet"

      - name: Fast-forward merge trunk into trunk-cached
        run: |
          git merge --ff-only ${{ github.sha }}

      - name: Push updated trunk-cached branch
        run: |
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
