name: Test Cached Tag Workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  update-trunk-cached:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Git log test
        run: |
          git fetch origin trunk trunk-cached
          echo
          echo
          git log origin/trunk
          echo
          echo
          git log origin/trunk-cached
          

      - name: Update trunk-cached branch
        run: |
          if git fetch origin trunk-cached; then
            git switch trunk-cached
            echo 'before rebase'
            git rebase origin/trunk-cached
            echo 'after rebase'
          else
            git switch -c trunk-cached
            echo "No trunk-cached branch exists yet"
          fi
          echo 'before merge'
          git merge --ff-only ${{ github.sha }} --allow-unrelated-histories
          echo 'after merge'
          git push origin trunk-cached
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
